# Generated by Django 5.0.6 on 2024-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.AddField(
            model_name='education',
            name='institution_image',
            field=models.ImageField(blank=True, null=True, upload_to='institution_image/'),
        ),
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
