# Generated by Django 5.0.6 on 2024-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio_app', '0002_remove_education_degree_education_institution_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='status',
            new_name='completed',
        ),
    ]
