# Generated by Django 5.0.6 on 2024-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio_app', '0004_remove_project_project_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_client', models.IntegerField()),
                ('project_completed', models.IntegerField()),
                ('certification', models.IntegerField()),
                ('experience_year', models.IntegerField()),
            ],
        ),
    ]
