# Generated by Django 5.0.6 on 2024-10-02 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio_app', '0007_education_location_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificskill',
            name='general_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_skills', to='portofolio_app.generalskill'),
        ),
    ]
