# Generated by Django 5.0.6 on 2024-10-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio_app', '0009_generalskill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalskill',
            name='icon_class',
            field=models.CharField(help_text='FontAwesome or other icon class', max_length=50, null=True),
        ),
    ]
